//! # Ferrisp
//!
//! A parser combinator for a clojure-like lisp written with Parser Combinators.
//!

#[macro_use]
extern crate log;

#[cfg(not(target_env = "msvc"))]
use jemallocator::Jemalloc;

#[cfg(not(target_env = "msvc"))]
#[global_allocator]
static GLOBAL: Jemalloc = Jemalloc;

mod lib;

use rustyline::error::ReadlineError;
use rustyline::Editor;

use crate::lib::parser::Parser;
use crate::lib::types::{Ferr, Fexp};

static PROMPT: &'static str = "🦀λ> ";

/// Runs input string through Ferrisp's [`Parser`](./lib/parser/struct.Parser.html) and yields a
/// valid [`Fexp`](./lib/types/enum.Fexp.html); otherwise, return an
/// [`error`](./lib/types/enum.Ferr.html).
///
/// It should be noted that the resulting `Fexp` value is semantically equivalent to an AST. With
/// the output returned, basic evaluation and function application can be performed by traversing
/// the AST generated by the parser.
fn run(input: &str) -> Result<Fexp, Ferr> {
    let mut ast = Parser::parse(input)?;
    Ok(ast)
}

fn main() {
    env_logger::init();
    let mut rl = Editor::<()>::new();

    loop {
        let input = rl.readline(PROMPT);
        match input {
            Ok(line) => {
                rl.add_history_entry(line.as_str());
                match run(&line) {
                    Ok(o) => println!("{}", o.as_str()),
                    Err(e) => println!("Malformed Input: {:?}", e),
                }
            }
            Err(ReadlineError::Interrupted) => {
                println!("CTRL-C");
                break;
            }
            Err(ReadlineError::Eof) => {
                println!("CTRL-D");
                break;
            }
            Err(err) => {
                println!("Error: {:?}", err);
                break;
            }
        }
    }
}
